apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "ladder-api.fullname" . }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    jasyptEncryptorPassword: AgAVJb7fAGkTlp+C9Q0Wccwhwm9VPC1dLYBPQnT2MuIjZ94X2IqOUkUAtcqh068UAdgHNJfvlb/lYXXYr0yw+UWWOtaj2/mkSqvzDIrqL2mJs1FiyUAJAd8w+0wF739tukZ/U/4vmROxg5Meymxc4IsjabwSFOizdm9+2m9fgln5zR84LMZ2JlHTaQd28Bpifeu0hIbsFsteFWuu7pDL5eoo/yAB7BdRYAbQVnfEhvimCFm/il667IMZaedMCbc5E+j2F2ruAY592pV/rhGUz6Hv+zWWZPLLv0P7+P0WBbm/+wDYVGhAXQGOsyPdxISjQVdFJVUERS5jl2dN5L8+aOOTdDfh6iTypK6p1TA+K7bPrcb4HN+F19TwxysP+Qn+ezwGXfQLwGM5JXQ03Q+GHeuOoze/B3NdmjR+Qk2UEVrbV2oBEb6/J08tBae6Y+w46jU+V8SO0E9lEjYxo2Z9JPpUjOU6Z6uiN5BBnu3t/QlyG72mW9TFol1+oxnmydp6e4Ts2BB3dXGXW4oI3tDGZ0b1BACYR/WTpdF914hse9EFJm6S0U2RNAD3w7iMKGEIRZRH6KzLCwKta18k48eGRRvfgfFjJ3JKQk636S1V3MKYb4D2Uy8PMi1Zxo07df3TtNL2E95UFk4yIW8U0fIDHyRElWx/LZ80Zn4hTXacH9ts5OUJSlVGpS1zW+lsAtl1xgf6QMPP7hefwDCILuE=
