replicaCount: 2
image:
  repository: mashupladder/ladder-api
  pullPolicy: Always
  tag: 0.0.1-2894375829
env:
  SPRING_PROFILES_ACTIVE: dev
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations:
  prometheus.io/scrape: 'true'
  prometheus.io/port: '9000'
  prometheus.io/path: /api/monitoring/prometheus
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 9000
  targetPort: 9000
livenessProbe:
  path: /api/liveness
  port: http
readinessProbe:
  path: /api/readiness
  port: http
resources:
  requests:
    cpu: 100m
    memory: 256Mi
    ephemeral-storage: 2Gi
  limits:
    cpu: 500m
    memory: 512Mi
    ephemeral-storage: 4Gi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
