ingress:
  enabled: true
  className: ''
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
          servicePort: 9000
          serviceName: ladder-api
        - path: /search
          pathType: Prefix
          servicePort: 9001
          serviceName: ladder-search
  tls: [ ]
