ingress:
  enabled: true
  className: ''
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: dev.api.musily.app
      paths:
        - path: /
          pathType: Prefix
          servicePort: 9000
          serviceName: ladder-api-dev
        - path: /search
          pathType: Prefix
          servicePort: 9001
          serviceName: ladder-search-api-dev
  tls: [ ]
