replicaCount: 2
image:
  repository: mashupladder/ladder-search
  pullPolicy: Always
  tag: 0.0.2-2963886525
env:
  SPRING_PROFILES_ACTIVE: dev
  SECRET_YOUTUBE_VIDEO_KEY: ''
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations:
  prometheus.io/scrape: 'true'
  prometheus.io/port: '9001'
  prometheus.io/path: /search/monitoring/prometheus
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 9001
  targetPort: 9001
livenessProbe:
  path: /search/liveness
  port: http
readinessProbe:
  path: /search/readiness
  port: http
resources:
  requests:
    cpu: 0.1
    memory: 256Mi
    ephemeral-storage: 1Gi
  limits:
    cpu: 0.5
    memory: 512Mi
    ephemeral-storage: 4Gi
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
